version: '3.6'
services:
#  api-cash-flow:
#    image: api-cash-flow:1
#    restart: on-failure
#    ports:
#      - 8088:8088
#    depends_on:
#      - mongodb
#    networks:
#      - internal-net
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=db_cash_flow
volumes:
  mongo:

#networks:
#  internal-net:
#    driver: bridge
