apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-cash-flow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-cash-flow
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
